### ISSUE TITLE
Fails to Build

### ISSUE THREAD

**Issue by nh43de** [LanceMcCarthy/PDFCombiner#3]
When trying to build, I get the following error:

"The tag 'RadGridView' does not exist in XML namespace 'http://schemas.telerik.com/2008/xaml/presentation'. Line 21 Position 10.	PdfCombiner.Wpf	C:\code\Github\PDFCombiner\src\PdfCombiner.Wpf\Views\CombinerView.xaml"

Looks like the project is missing references.

**Comment by LanceMcCarthy** [comment]
You're mostly likely having the issue because the project has references to R3 2019. You can fix this by updating the assembly references to the ones in your current UI for WPF installation folder here:

`C:\Program Files (x86)\Progress\Telerik UI for WPF R1 2020\Binaries.NoXaml\WPF45\`

Note: I cannot post a release build because this is a demo using trial assemblies. If you do not have a UI for WPF license, you can start a trial here - https://www.telerik.com/products/wpf/overview.aspx

**Comment by LanceMcCarthy** [comment]
Hi Nathan, 

I've gone ahead and updated the references to R1 2020. As long as you have it installed, it should build as-is (trial or dev assemblies, they both in the same path).

Let me know if you have any further trouble.

**Comment by nh43de** [comment]
Ah got it, thank you - thanks for posting this is a cool proof of concept!

**Comment by LanceMcCarthy** [comment]
Thank you for bringing this to my attention, sometimes it's hard to keep track of all the demo versions :) 

I typically use the Telerik NuGet server for most of my demos, but in the case of WPF, the Trial packages has a ".Trial" at the end of the name. so you would have to uninstall the trial packages and install the dev version. Using assembly references is easier for you because the actual assembly names and their install location are the same regardless of license type.

I'm going to  mark this issue as closed, don't hesitate to open a new issue if you have any new problems.
